#!/bin/bash

git add .
echo "Enter commit message you idiot!"
read message
git commit -m "$message"
git push



sleep 0.5
echo 'Here'
sleep 0.5
echo 'We'
sleep 0.5
echo 'Gooooooo'

sleep 0.1
echo '.'
sleep 0.1
echo '.'
sleep 0.1
echo '.'
sleep 0.1
echo '.'